### ISSUE TITLE
Inconsistent ConnectionError during select 

### ISSUE THREAD

**Issue by dmanojbabu** [vertica/vertica-python#178]
Getting below inconsistent ConnectionError during select queries only. If run my script after some time it works without issue. 

How to find the exact issue and the error message was clear?
Any help will be appreciated.

Traceback (most recent call last):
  File "generator.py", line 48, in execute
    target.mxm(mxm_sql)
  File "/home/itsme/Target.py", line 38, in mxm
    curs.execute(sql, parms)
  File "build/bdist.linux-x86_64/egg/vertica_python/vertica/cursor.py", line 113, in execute
    self._message = self.connection.read_message()
  File "build/bdist.linux-x86_64/egg/vertica_python/vertica/connection.py", line 206, in read_message
    raise_from(errors.ConnectionError, e)
  File "/data/itsme/Python-2.7.12/lib/python2.7/site-packages/six-1.11.0-py2.7.egg/six.py", line 737, in raise_from
    raise value
ConnectionError

**Comment by jhpierce** [comment]
I'm also experiencing this in vertica-python `0.7.3`, python `2.7`. Any update on whether `0.7.4` or later releases fixes this issue?

**Comment by sitingren** [comment]
@jhpierce From the error message I cannot get useful debug info. Could you please modify file `xxxxx/vertica_python/vertica/connection.py` (figure out the specific path according to your error message), in read_message, replace `raise_from(errors.ConnectionError, e)` with `raise e`, and then run your program again? I hope this can reveal more info.

**Comment by sitingren** [comment]
@jhpierce No problem, I'm happy to help.
