### ISSUE TITLE
connect error

### ISSUE THREAD

**Issue by andyliusi** [vertica/vertica-python#186]
ERROR:root:Connect vertica database error with address:10.161.180.16
AttributeError
False
Traceback (most recent call last):
  File "D:/code/test-v1.py", line 16, in connect
    self.connection = vertica_python.connect(**self.conn_info)
  File "C:\Users\l00440039\AppData\Local\Enthought\Canopy32\User\lib\site-packages\vertica_python\vertica\connection.py", line 25, in connect
    return Connection(kwargs)
  File "C:\Users\l00440039\AppData\Local\Enthought\Canopy32\User\lib\site-packages\vertica_python\vertica\connection.py", line 44, in __init__
    self.startup_connection()
  File "C:\Users\l00440039\AppData\Local\Enthought\Canopy32\User\lib\site-packages\vertica_python\vertica\connection.py", line 260, in startup_connection
    self.write(messages.Startup(user, database))
  File "C:\Users\l00440039\AppData\Local\Enthought\Canopy32\User\lib\site-packages\vertica_python\vertica\connection.py", line 179, in write
    raise_from(errors.ConnectionError, e)
  File "C:\Users\l00440039\AppData\Local\Enthought\Canopy32\User\lib\site-packages\six.py", line 718, in raise_from
    raise value
ConnectionError

it is remote connection,i installed the driver, when the software execute to " raw_socket.connect((host, port))" step by step ,it will throw an exception "coudn't send message",but i still don't the real reason

**Comment by dennisobrien** [comment]
Hi @andyliusi 

Can you provide details on the version of Python you are running and the version of vertica-python installed?

I'm trying to track down a similar issue.  In one environment (Python 3.6, vertica-python 0.7.3) I'm getting the same traceback you mentioned above.  In another environment (Python 3.5, vertica-python 0.7.3) it works.  There may be some other differences so I'm not ready to say this is 3.6 versus 3.5.  So I'm curious what your configuration is.

thanks,
Dennis

**Comment by sitingren** [comment]
@andyliusi Have you solved the problem? Our improvements (commit 029a65a) posted on `master` branch (even though not included in a release yet) is able to write connection status into log. Hope the log can provide clues to you.

**Comment by sitingren** [comment]
Close this issue because it has not had recent activity.
