### ISSUE TITLE
Add Identity Data Type Support

### ISSUE THREAD

**Issue by jordiyeh** [vertica/vertica-python#246]
When trying to use SQLAlchemy with vertica-python and sqlalchemy-vertica-python, a simple model like the following

class Person(db.Model):
    id = db.Column(db.Integer, primary_key=True)

will result in an error 

Type "SERIAL" does not exist'

and the SQL will try to create the following DDL

CREATE TABLE "Person" ( \tid SERIAL NOT NULL,

This can be enhanced, if the Identity data type is included

https://www.vertica.com/docs/9.2.x/HTML/Content/Authoring/AdministratorsGuide/Sequences/AutoIncrementIdentitySequences.htm

**Comment by sitingren** [comment]
I think this is a problem of sqlalchemy-vertica, not vertica-python. vertica-python does not prevent you from defining an AUTO_INCREMENT/IDENTITY column. You'd better post your request at sqlalchemy-vertica's Github page.

**Comment by jordiyeh** [comment]
@sitingren Thanks for the response. I will take a look at sqlalchemy-vertical, but I don't see any references to sqlalchemy-vertica-python package in the following traceback.

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/pyvirtualenv/flaskaqlalchemy/lib/python3.6/site-packages/flask_sqlalchemy/__init__.py", line 963, in create_all
    self._execute_for_all_tables(app, bind, 'create_all')
  File "/pyvirtualenv/flaskaqlalchemy/lib/python3.6/site-packages/flask_sqlalchemy/__init__.py", line 955, in _execute_for_all_tables
    op(bind=self.get_engine(app, bind), **extra)
  File "/pyvirtualenv/flaskaqlalchemy/lib/python3.6/site-packages/sqlalchemy/sql/schema.py", line 4005, in create_all
    tables=tables)
  File "/pyvirtualenv/flaskaqlalchemy/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1940, in _run_visitor
    conn._run_visitor(visitorcallable, element, **kwargs)
  File "/pyvirtualenv/flaskaqlalchemy/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1549, in _run_visitor
    **kwargs).traverse_single(element)
  File "/pyvirtualenv/flaskaqlalchemy/lib/python3.6/site-packages/sqlalchemy/sql/visitors.py", line 121, in traverse_single
    return meth(obj, **kw)
  File "/pyvirtualenv/flaskaqlalchemy/lib/python3.6/site-packages/sqlalchemy/sql/ddl.py", line 757, in visit_metadata
    _is_metadata_operation=True)
  File "/pyvirtualenv/flaskaqlalchemy/lib/python3.6/site-packages/sqlalchemy/sql/visitors.py", line 121, in traverse_single
    return meth(obj, **kw)
  File "/pyvirtualenv/flaskaqlalchemy/lib/python3.6/site-packages/sqlalchemy/sql/ddl.py", line 791, in visit_table
    include_foreign_key_constraints=include_foreign_key_constraints
  File "/pyvirtualenv/flaskaqlalchemy/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 948, in execute
    return meth(self, multiparams, params)
  File "/pyvirtualenv/flaskaqlalchemy/lib/python3.6/site-packages/sqlalchemy/sql/ddl.py", line 68, in _execute_on_connection
    return connection._execute_ddl(self, multiparams, params)
  File "/pyvirtualenv/flaskaqlalchemy/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1009, in _execute_ddl
    compiled
  File "/pyvirtualenv/flaskaqlalchemy/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1200, in _execute_context
    context)
  File "/pyvirtualenv/flaskaqlalchemy/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1413, in _handle_dbapi_exception
    exc_info
  File "/pyvirtualenv/flaskaqlalchemy/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 265, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/pyvirtualenv/flaskaqlalchemy/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 248, in reraise
    raise value.with_traceback(tb)
  File "/pyvirtualenv/flaskaqlalchemy/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1193, in _execute_context
    context)
  File "/pyvirtualenv/flaskaqlalchemy/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 509, in do_execute
    cursor.execute(statement, parameters)
  File "/pyvirtualenv/flaskaqlalchemy/lib/python3.6/site-packages/vertica_python/vertica/cursor.py", line 152, in execute
    raise errors.QueryError.from_error_response(self._message, operation)
sqlalchemy.exc.ProgrammingError: (vertica_python.errors.QueryError) Severity: b'ERROR', Message: b'Type "SERIAL" does not exist', Sqlstate: b'42704', Routine: b'typenameTypeId', File: b'parse_type.c', Line: b'236', SQL: ' CREATE TABLE "user" ( \tid SERIAL NOT NULL,  \tusername VARCHAR(80),  \temail VARCHAR(120),  \tPRIMARY KEY (id),  \tUNIQUE (username),  \tUNIQUE (email) ) ' [SQL: '\nCREATE TABLE "user" (\n\tid SERIAL NOT NULL, \n\tusername VARCHAR(80), \n\temail VARCHAR(120), \n\tPRIMARY KEY (id), \n\tUNIQUE (username), \n\tUNIQUE (email)\n)\n\n'] (Background on this error at: http://sqlalche.me/e/f405)

**Comment by jordiyeh** [comment]
Thanks. Let me check further.
