### ISSUE TITLE
COPY... FROM LOCAL does not work.

### ISSUE THREAD

**Issue by bambrozio** [vertica/vertica-python#391]
The command `COPY... FROM LOCAL` works perfectly with `vsql`:
```
db=> COPY my_schema.table_name FROM LOCAL '/Users/bambrozio/file.csv' PARSER fcsvparser() ABORT ON ERROR
```

However, it doesn't via `vertica-python`. I've tried with latest realease (`pip install vertica-python --upgrade` and also with latest commit from git (see below)):
```
$ python --version
Python 3.8.3

$ pip install git+https://github.com/vertica/vertica-python.git@master
Collecting git+https://github.com/vertica/vertica-python.git@master
  Cloning https://github.com/vertica/vertica-python.git (to revision master) to /private/var/folders/py/sj4b7y1d3m7_4566n57shb040000gn/T/pip-req-build-kvy8p78m
  Running command git clone -q https://github.com/vertica/vertica-python.git /private/var/folders/py/sj4b7y1d3m7_4566n57shb040000gn/T/pip-req-build-kvy8p78m
Requirement already satisfied (use --upgrade to upgrade): vertica-python==0.10.4 from git+https://github.com/vertica/vertica-python.git@master in /Users/bambrozio/miniconda3/
envs/proj/lib/python3.8/site-packages
Requirement already satisfied: python-dateutil>=1.5 in /Users/bambrozio/miniconda3/envs/proj/lib/python3.8/site-packages (from vertica-python==0.10.4) (2.8.1)
Requirement already satisfied: six>=1.10.0 in /Users/bambrozio/miniconda3/envs/proj/lib/python3.8/site-packages (from vertica-python==0.10.4) (1.15.0)
Building wheels for collected packages: vertica-python
  Building wheel for vertica-python (setup.py) ... done
  Created wheel for vertica-python: filename=vertica_python-0.10.4-py3-none-any.whl size=167779 sha256=87d54c3ff203becfda5221c650b670a527d6a7f285797ef0c336f78a1f154543
  Stored in directory: /private/var/folders/py/sj4b7y1d3m7_4566n57shb040000gn/T/pip-ephem-wheel-cache-yy4mjqmy/wheels/83/dd/80/0990ed38275025442bde4f1a2d715806f04e46e7695da5
53f9
Successfully built vertica-python

$ python

>>> import vertica_python
>>> def get_conn_params():
...     return dict(
...         host='host.name.went.here',
...         port=5433,
...         user='user.went.here',
...         password='pass.went.here',
...         database='db',
...         session_label='test',
...         unicode_error='strict',
...         ssl=False,
...         use_prepared_statements=False,
...         disable_copy_local=False,
...         )

>>> query = "COPY my_schema.table_name FROM LOCAL '/Users/bambrozio/file.csv' PARSER fcsvparser() ABORT ON ERROR"
>>> ds = get_conn_params()
>>> connection = vertica_python.connect(**ds)
>>> cur = connection.cursor()
>>> cur.execute(query, buffer_size=65536)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: execute() got an unexpected keyword argument 'buffer_size'
```

If I try without the `buffer_size` I get different error:
```
>>> cur.execute(query)
<vertica_python.vertica.cursor.Cursor object at 0x7fcfd71d0ac0>
>>> print("Rows loaded:", cur.fetchall())
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/bambrozio/miniconda3/envs/proj/lib/python3.8/site-packages/vertica_python/vertica/cursor.py", line 303, in fetchall
    return list(self.iterate())
  File "/Users/bambrozio/miniconda3/envs/proj/lib/python3.8/site-packages/vertica_python/vertica/cursor.py", line 365, in iterate
    row = self.fetchone()
  File "/Users/bambrozio/miniconda3/envs/proj/lib/python3.8/site-packages/vertica_python/vertica/cursor.py", line 284, in fetchone
    raise errors.MessageError('Unexpected fetchone() state: {}'.format(
vertica_python.errors.MessageError: Unexpected fetchone() state: Unknown
```

**Comment by sitingren** [comment]
I think you may try to uninstall vertica-python and install from the latest commit from git again.

**Comment by sitingren** [comment]
Reopen if you have further questions, thanks.
