### ISSUE TITLE
Trying to insert a varchar value of length more than the actual defined length of the column does not throws an error

### ISSUE THREAD

**Issue by moledoc** [vertica/vertica-python#424]
We are using vertica-python to connect from linux to vertica (on linux).
When we try to insert a varchar value of length more than the actual defined length of the column then cursor.execute does not return an error (also nothing is inserted into the target  table) and the program just continues to run.
This makes debugging really difficult.

For example, we have table

```sql
create table test (
     col   varchar(10)
);
```

When trying to insert into it

```sql
create local temporary table tmp on commit preserve rows as
select '12345678901' as col
;
insert into test
select col
from tmp
;
commit;
```

the expected result is 

```sql
SQL Error [8682] [22001]: [Vertica][VJDBC](8682) ERROR: String of 11 octets is too long for type Varchar(10) for column col
```

However, when trying to insert into this table using vertica-python, no error is thrown.
Am I missing something? When testing using

```sql
insert into test (col) 
values ('12345678901')
;
commit;
```

then vertica-python gave the expected result.

**Comment by sitingren** [comment]
Usually, you have to run `cursor.fetchall()` after `cursor.execute()`, so that all possible error for this statement can be thrown.

**Comment by moledoc** [comment]
I am running `cursor.fetchall()` after `cursor.execute()`, but no error is thrown.

**Comment by sitingren** [comment]
@moledoc would you please provide your code so that we can reproduce it? Thanks.

**Comment by h-serizawa** [comment]
@moledoc I saw the exception occurred using with for auto connection closing as below.

```
query = """
INSERT INTO test (col) VALUES ('12345678901');
"""

with vertica_python.connect(**conn_info) as connection:
    cur = connection.cursor()
    cur.execute(query)
```

```
# python3 Github-VerticaPython-Issue424.py 
Traceback (most recent call last):
  File "/tmp/work/Github-VerticaPython-Issue424.py", line 21, in <module>
    cur.execute(query)
  File "/tmp/work/lib/python3.9/site-packages/vertica_python/vertica/cursor.py", line 222, in execute
    self._execute_simple_query(operation)
  File "/tmp/work/lib/python3.9/site-packages/vertica_python/vertica/cursor.py", line 606, in _execute_simple_query
    raise errors.QueryError.from_error_response(self._message, query)
vertica_python.errors.QueryError: Severity: ERROR, Message: String of 11 octets is too long for type Varchar(10) for column col, Sqlstate: 22001, Routine: annotateExceptionWithColNameAndThrow, File: /data/jenkins/workspace/RE-ReleaseBuilds/RE-Jackhammer_2/server/vertica/Proc/ProcClauses.cpp, Line: 619, Error Code: 8682, SQL: " INSERT INTO test (col) VALUES ('12345678901'); "
```

**Comment by moledoc** [comment]
@h-serizawa I got the same error with

```sql
INSERT INTO test (col) VALUES ('12345678901');
```

 and this is the expected result, as I mentioned above. I need to get the same error when trying to insert from a temporary table.

@sitingren here is an analogous (but somewhat redacted) example of my code. Let's assume the target table is the same as mentioned above.

```py
import vertica_python
import json
import pandas as pd
from sys import modules
from dataclasses import dataclass

class Connection():
    def __init__(self,driver:modules , parameters:dict):
        self.driver = driver
        self.parameters = parameters
        self.conn = None
        self.cursor = None
        self.latest_result = None

    def __enter__(self):
        self.conn = self.driver.connect(**self.parameters)
        self.cursor = self.conn.cursor()
        return self.conn

    def __exit__(self, exc_type, exc_val, exc_tb):
        self.conn.close()

    def execute(
        self
        ,sql:str
    ) -> None:
        self.cursor.execute(sql)
        last_fetch =self.cursor.fetchall()
        self.latest_result = pd.DataFrame(last_fetch)

# dataclass to hold runtime info needed in different functions and templates
@dataclass
class Info:
    conn:Connection

def get_connection() -> Connection:
    connection_file_path = "/path/to/connection/file.json"
    connection_timeout = 600
    with open(connection_file_path) as f:
        conn_info = json.load(f)
    # additional connection parameters, that are not in connection_file.json
    conn_info["autocommit"] = False
    conn_info["connection_timeout"] = connection_timeout
    conn_info["unicode_error"] = "strict"
    return  Connection(driver = vertica_python,parameters=conn_info)

def load_table() -> None:
    conn = get_connection()
    info = Info(
        conn=conn
    )
    with conn:
        # does not throw an error
        info.conn.execute(
            sql = """
            create local temporary table tmp on commit preserve rows as
            select '12345678901' as col
            ;
            insert into test
            select col
            from tmp
            ;
            commit;
            """
        )
        # also does not throw an error
        info.conn.execute(
            sql = """
            create local temporary table tmp2 on commit preserve rows as
            select '1234567890' as col
            ;
            insert into non_existing_table
            select col
            from tmp2
            commit;
            """
        )
        # print(info.conn.latest_result)

load_table()
```

**Comment by h-serizawa** [comment]
@moledoc You missed calling `cursor.nextset()` to execute the rest of the queries you specified in one string variable. Without calling `cursor.nextset()`, your code executes only the first query. You can see the exception with the following code.

```
query = """
create local temporary table tmp on commit preserve rows as
select '12345678901' as col
;
insert into test
select col
from tmp
;
commit;
"""

with vertica_python.connect(**conn_info) as connection:
    cur = connection.cursor()
    cur.execute(query)
    while True:
        cur.fetchall()
        if cur.nextset() == False:
            break
```

**Comment by moledoc** [comment]
@h-serizawa this solved my issue. Thank you very much!
