### ISSUE TITLE
socket.timeout: timed out

### ISSUE THREAD

**Issue by raebralop** [vertica/vertica-python#466]
### Description
I start a query, if I set the query date as early as '2013-01-01' , then the query will timeout in around 18 seconds.
python:3.9.7

### Error Message
```
Traceback (most recent call last):
  File "C:\Users\larry\anaconda3\lib\site-packages\vertica_python\vertica\connection.py", line 655, in read_message
    type_ = self.read_bytes(1)
  File "C:\Users\larry\anaconda3\lib\site-packages\vertica_python\vertica\connection.py", line 716, in read_bytes
    result = self._socket_as_file().read(1)
  File "C:\Users\larry\anaconda3\lib\socket.py", line 704, in readinto
    return self._sock.recv_into(b)
socket.timeout: timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "e:\tang_task\connect_vertica.py", line 114, in <module>
    task.vquery(game='ue', sql_file=u'UE_query_years.sql',out_csv=f'result_ue_{query_date_list}.csv',query_date_list=query_date_list)
  File "e:\tang_task\connect_vertica.py", line 97, in vquery
    cur.execute(c)
  File "C:\Users\larry\anaconda3\lib\site-packages\vertica_python\vertica\cursor.py", line 238, in execute
    self._execute_simple_query(operation)
  File "C:\Users\larry\anaconda3\lib\site-packages\vertica_python\vertica\cursor.py", line 656, in _execute_simple_query
    self._message = self.connection.read_message()
  File "C:\Users\larry\anaconda3\lib\site-packages\vertica_python\vertica\connection.py", line 689, in read_message
    raise_from(errors.ConnectionError(str(e)), e)
  File "<string>", line 3, in raise_from
vertica_python.errors.ConnectionError: timed out
```
### part of python code
```
        conn = vertica_python.connect(**conn_info)
        cur = conn.cursor()
        cur.execute(c)  <------------------------Here c is a heavy sql query task string from year 2013.
        result = cur.fetchall()
        conn.close()
```

### part of sql code
```
SELECT distinct 
            owner_id,
            min(date(created_at)) as firstpaydt,
            substr(date(created_at)::varchar,1,7) as firstpayyrmo
FROM event_track
WHERE track_id in ('purchase', 'purchase_android') and date(created_at)>='2013-01-01'
GROUP BY owner_id,firstpayyrmo
```

**Comment by raebralop** [comment]
problem found, 'connection_timeout': 20
