### ISSUE TITLE
Unable to decode messages

### ISSUE THREAD

**Issue by azdobylak** [vertica/vertica-python#493]
After migration to Vertica 12.0.3 (from 12.0.1) I have an issue with decoding messages. I am using cluster with 3 nodes, running query on 3rd node returns an error:
```
conn_info = {
    'user': '***',
    'password': '***',
    'host': '<node3>',
    'port': 5433,
    'database': 'vertica_db',
    'unicode_error': 'ignore',
}

connection = vertica_python.connect(**conn_info)
cur = connection.cursor()
cur.execute('select 3;')
print(cur.fetchone())
```

```
Traceback (most recent call last):
File "test_vertica_python.py", line 14, in <module>
print(cur.fetchone())
File "/home/user/.pyenv/versions/tsg-scripts/lib/python3.7/site-packages/vertica_python/vertica/cursor.py", line 330, in fetchone
self._message = self.connection.read_message()
File "/home/user/.pyenv/versions/tsg-scripts/lib/python3.7/site-packages/vertica_python/vertica/connection.py", line 694, in read_message
message = BackendMessage.from_type(type_, self.read_bytes(size - 4))
File "/home/user/.pyenv/versions/tsg-scripts/lib/python3.7/site-packages/vertica_python/vertica/messages/message.py", line 102, in from_type
return klass(data, **kwargs)
File "/home/user/.pyenv/versions/tsg-scripts/lib/python3.7/site-packages/vertica_python/vertica/messages/backend_messages/command_complete.py", line 58, in __init__
self.command_tag = data.decode('utf-8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd0 in position 0: unexpected end of data
```

At the same time the query executes correctly on 1st and 2nd node. The issue also occurred on 2nd node, and for some time worked on 3rd node. 
The issue was spotted only with vertica_python, it works fine with pyodbc and vsql, so I suppose it is possible to improve response handling. I'm using `vertica_python==1.3.1`. To exclude network issue I reproduced the issue on the server (executed the script locally), the error was the same.

**Comment by azdobylak** [comment]
I tried to debug the issue, I check the [value of fetched bytes](https://github.com/vertica/vertica-python/blob/master/vertica_python/vertica/connection.py#L694) on working and bugged host.

- Correct one returns: `type: b'C', size: 5, bytes: b'\x00'`
- Incorrect host: `type: b'C', size: 6, bytes: b'\xc2\x00'`

If I blindly overwrite the value `C2 00` to `00` and proceed then it works, returns correct result. Would appreciate help from someone who actually understands the meaning of these codes.

**Comment by azdobylak** [comment]
- At first, it looked so. But we just upgraded dev environment and I was unable to reproduce the error there. No relation to client upgrade - same error with `vertica_python==1.0.5`.
- Yes
- TLS off
- Yes. When I replaced `select 3;` with `select <column> from <table>;` then it proceeds to [RowDescription branch](https://github.com/vertica/vertica-python/blob/fe96db77000bec714e0e4cc534dc80989ea37d13/vertica_python/vertica/connection.py#L691) and returns correct response

**Comment by BoneArch** [comment]
--------------------------------------------------------------------------------
command tag length: 1
command tag content: b'\xaf'
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xaf in position 0: invalid start byte
Server version: 12.0.4
Query executed (if possible): xxx
The OS of each server node (if possible): CentOS 7.9.2009
The locale of each server node (if possible): en_US@collation=binary
--------------------------------------------------------------------------------

**Comment by chathawee** [comment]
I also got the same error on the version 1.3.2
This is the error `vertica error: 'utf-8' codec can't decode byte 0xe9 in position 1: invalid continuation byte`

**Comment by chathawee** [comment]
@sitingren Did you mean Vertica to version 12.0.4-3 right?
